### ISSUE TITLE
未找到引用的函数在plt.sec分析时报错

### ISSUE THREAD

**Issue by hu4i** [veritas501/PltResolver#1]
（IDA 7.0）如果plt.sec中的某项没有找到引用的话，IDA不能分析出它是一个thunk函数，idaapi.get_func()会返回None，导致产生错误。
```python
				# rename plt.sec
				for addr in idautils.DataRefsTo(r_off):
					plt_sec_func = idaapi.get_func(addr).startEA
```

**Comment by veritas501** [comment]
方便提供一个能触发这个bug的binary吗

**Comment by hu4i** [comment]
发到QQ邮箱了，在memset函数会报错

**Comment by veritas501** [comment]
看起来是导入memset但没有使用导致ida分析时没有将他create function导致的，加了下判断应该就行了
